version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kreatives-backend
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    environment:
      APP_ENV: local
      APP_KEY: base64:8QBgU7jExJLr1wqee1t4Cgcw0ESK2P6VChyTVy8Hyr4=
      APP_DEBUG: true
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: kreatives
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "php artisan migrate --seed && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kreatives-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev -- --host
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: kreatives-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kreatives
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: