version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: kreative-backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    networks:
      - kreative
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: kreative
      DB_USERNAME: root
      DB_PASSWORD: root

  frontend:
    build:
      context: ./frontend
    container_name: kreative-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - kreative
    command: npm run dev

  nginx:
    image: nginx:stable
    container_name: kreative-nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - kreative

  mysql:
    image: mysql:8.0
    container_name: kreative-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kreative
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - kreative

volumes:
  mysql-data:

networks:
  kreative:
    driver: bridge
